steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.yaml
      - build

    env:
    - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
    - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
    - 'NEXT_PUBLIC_GTAG_ID=${_NEXT_PUBLIC_GTAG_ID}'
    - 'NEXT_PUBLIC_FCM_VAPID_KEY=${_NEXT_PUBLIC_FCM_VAPID_KEY}'
    - 'NEXT_PUBLIC_SUPABASE_STROAGE_PREFIX_URL=${_NEXT_PUBLIC_SUPABASE_STROAGE_PREFIX_URL}'
    - 'NEXT_PUBLIC_FCM_API_KEY=${_NEXT_PUBLIC_FCM_API_KEY}'
    - 'NEXT_PUBLIC_REST_API=${_NEXT_PUBLIC_REST_API}'
    - 'NEXT_PUBLIC_NODE_ENV=${_NEXT_PUBLIC_NODE_ENV}'
    - 'NEXT_PUBLIC_ADMIN_ID=${_NEXT_PUBLIC_ADMIN_ID}'
    - 'NEXT_PUBLIC_SENTRY_AUTH_TOKEN=${_NEXT_PUBLIC_SENTRY_AUTH_TOKEN}'
    - 'SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}'
    - 'SENTRY_LOG_LEVEL=${_SENTRY_LOG_LEVEL}'

  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.yaml
      - push

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args:
  #     [
  #       'set',
  #       'image',
  #       'deployment/shaki-back',
  #       'shaki-registry-sha256-1=asia.gcr.io/imposing-coast-358400/shaki-registry:3',
  #     ]
  #   env:
  #     - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
  #     - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1
