steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia.gcr.io/artinfo-398400/artinfo-frontend:1.0' 
      - '.'  # Dockerfile의 위치 (현재 디렉토리)

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia.gcr.io/artinfo-398400/artinfo-frontend:1.0' 
