FROM node:16

WORKDIR /artinfo/

COPY package.json yarn.lock /artinfo/

RUN yarn install

COPY . /artinfo/

EXPOSE 3000

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_GTAG_ID
ARG NEXT_PUBLIC_FCM_VAPID_KEY
ARG NEXT_PUBLIC_SUPABASE_STROAGE_PREFIX_URL
ARG NEXT_PUBLIC_FCM_API_KEY
ARG NEXT_PUBLIC_REST_API
ARG NEXT_PUBLIC_NODE_ENV
ARG NEXT_PUBLIC_ADMIN_ID
ARG NEXT_PUBLIC_SENTRY_AUTH_TOKEN
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_LOG_LEVEL

RUN yarn build --env NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
                --env NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
                --env NEXT_PUBLIC_GTAG_ID=$NEXT_PUBLIC_GTAG_ID \
                --env NEXT_PUBLIC_FCM_VAPID_KEY=$NEXT_PUBLIC_FCM_VAPID_KEY \
                --env NEXT_PUBLIC_SUPABASE_STROAGE_PREFIX_URL=$NEXT_PUBLIC_SUPABASE_STROAGE_PREFIX_URL \
                --env NEXT_PUBLIC_FCM_API_KEY=$NEXT_PUBLIC_FCM_API_KEY \
                --env NEXT_PUBLIC_REST_API=$NEXT_PUBLIC_REST_API \
                --env NEXT_PUBLIC_NODE_ENV=$NEXT_PUBLIC_NODE_ENV \
                --env NEXT_PUBLIC_ADMIN_ID=$NEXT_PUBLIC_ADMIN_ID \
                --env NEXT_PUBLIC_SENTRY_AUTH_TOKEN=$NEXT_PUBLIC_SENTRY_AUTH_TOKEN \
                --env SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN \
                --env SENTRY_LOG_LEVEL=$SENTRY_LOG_LEVEL

CMD ["yarn", "start"]
