name: deploy

on:
  push:
    branches:
      - main

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - name: Run scripts on server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=/home/ubuntu/.nvm
            source /home/ubuntu/.nvm/nvm.sh
            cd artinfo
            git pull origin main
            yarn install 
            yarn run build
            pm2 restart ecosystem.config.js
